- name: pipeline playbook
  hosts: dev
  become: yes
  gather_facts: no
  tasks:

  - name: install package epel-release
    yum:
      name: epel-release
      state: present

  - name: install pip
    yum:
      name: python-pip
      state: present
  
  - name: upgrade pip
    shell : pip install --upgrade pip
  
  - name: pip install docker-py
    pip:
      name:
        - docker
        - docker-compose
  
  - name: run container
    docker_container:
      name: wartest
      image: registry.gitlab.com/soltaniahmedamine/jenkins-tests/pipeline-ci-cd:latest
      ports: 80:8080
      state: started